<?xml version="1.0" encoding="UTF-8"?>
<kml xmlns="http://www.opengis.net/kml/2.2" xmlns:gx="http://www.google.com/kml/ext/2.2" xmlns:kml="http://www.opengis.net/kml/2.2" xmlns:atom="http://www.w3.org/2005/Atom">
<Document>
<open>1</open>
<Style id="styleDaimonCapacitor0"><IconStyle><scale>1.00</scale><Icon><href>http://maps.google.com/mapfiles/kml/paddle/grn-blank.png</href></Icon><hotSpot x="1" y="32" xunits="pixels" yunits="pixels"/></IconStyle><LabelStyle><color>ffffffff</color><colorMode>normal</colorMode><scale>1.00</scale></LabelStyle><ListStyle><ItemIcon><href>http://maps.google.com/mapfiles/kml/paddle/grn-blank.png</href></ItemIcon></ListStyle></Style>
<Style id="styleDaimonCapacitor1"><IconStyle><scale>1.00</scale><Icon><href>http://maps.google.com/mapfiles/kml/paddle/grn-blank.png</href></Icon><hotSpot x="1" y="32" xunits="pixels" yunits="pixels"/></IconStyle><LabelStyle><color>ffffffff</color><colorMode>normal</colorMode><scale>1.00</scale></LabelStyle><ListStyle><ItemIcon><href>http://maps.google.com/mapfiles/kml/paddle/grn-blank.png</href></ItemIcon></ListStyle></Style>
<StyleMap id="mapDaimonCapacitor"><Pair><key>normal</key><styleUrl>#styleDaimonCapacitor0</styleUrl></Pair><Pair><key>highlight</key><styleUrl>#styleDaimonCapacitor1</styleUrl></Pair></StyleMap>
<Style id="styleDaimonCapacitorSerie0"><IconStyle><scale>0.60</scale><Icon><href>http://maps.google.com/mapfiles/kml/paddle/ylw-circle.png</href></Icon><hotSpot x="1" y="32" xunits="pixels" yunits="pixels"/></IconStyle><LabelStyle><color>ff00ffff</color><colorMode>normal</colorMode><scale>0.60</scale></LabelStyle><ListStyle><ItemIcon><href>http://maps.google.com/mapfiles/kml/paddle/ylw-circle.png</href></ItemIcon></ListStyle></Style>
<Style id="styleDaimonCapacitorSerie1"><IconStyle><scale>0.60</scale><Icon><href>http://maps.google.com/mapfiles/kml/paddle/ylw-circle.png</href></Icon><hotSpot x="1" y="32" xunits="pixels" yunits="pixels"/></IconStyle><LabelStyle><color>ff00ffff</color><colorMode>normal</colorMode><scale>0.60</scale></LabelStyle><ListStyle><ItemIcon><href>http://maps.google.com/mapfiles/kml/paddle/ylw-circle.png</href></ItemIcon></ListStyle></Style>
<StyleMap id="mapDaimonCapacitorSerie"><Pair><key>normal</key><styleUrl>#styleDaimonCapacitorSerie0</styleUrl></Pair><Pair><key>highlight</key><styleUrl>#styleDaimonCapacitorSerie1</styleUrl></Pair></StyleMap>
<Style id="styleDaimonChave0"><IconStyle><scale>0.60</scale><Icon><href>http://maps.google.com/mapfiles/kml/paddle/red-circle.png</href></Icon><hotSpot x="1" y="32" xunits="pixels" yunits="pixels"/></IconStyle><LabelStyle><color>ff0000ff</color><colorMode>normal</colorMode><scale>0.60</scale></LabelStyle><ListStyle><ItemIcon><href>http://maps.google.com/mapfiles/kml/paddle/red-circle.png</href></ItemIcon></ListStyle></Style>
<Style id="styleDaimonChave1"><IconStyle><scale>0.60</scale><Icon><href>http://maps.google.com/mapfiles/kml/paddle/red-circle.png</href></Icon><hotSpot x="1" y="32" xunits="pixels" yunits="pixels"/></IconStyle><LabelStyle><color>ff0000ff</color><colorMode>normal</colorMode><scale>0.60</scale></LabelStyle><ListStyle><ItemIcon><href>http://maps.google.com/mapfiles/kml/paddle/red-circle.png</href></ItemIcon></ListStyle></Style>
<StyleMap id="mapDaimonChave"><Pair><key>normal</key><styleUrl>#styleDaimonChave0</styleUrl></Pair><Pair><key>highlight</key><styleUrl>#styleDaimonChave1</styleUrl></Pair></StyleMap>
<Style id="styleDaimonEP0"><IconStyle><scale>0.60</scale><Icon><href>http://maps.google.com/mapfiles/kml/paddle/ylw-circle.png</href></Icon><hotSpot x="1" y="32" xunits="pixels" yunits="pixels"/></IconStyle><LabelStyle><color>ff00ffff</color><colorMode>normal</colorMode><scale>0.60</scale></LabelStyle><ListStyle><ItemIcon><href>http://maps.google.com/mapfiles/kml/paddle/ylw-circle.png</href></ItemIcon></ListStyle></Style>
<Style id="styleDaimonEP1"><IconStyle><scale>0.60</scale><Icon><href>http://maps.google.com/mapfiles/kml/paddle/ylw-circle.png</href></Icon><hotSpot x="1" y="32" xunits="pixels" yunits="pixels"/></IconStyle><LabelStyle><color>ff00ffff</color><colorMode>normal</colorMode><scale>0.60</scale></LabelStyle><ListStyle><ItemIcon><href>http://maps.google.com/mapfiles/kml/paddle/ylw-circle.png</href></ItemIcon></ListStyle></Style>
<StyleMap id="mapDaimonEP"><Pair><key>normal</key><styleUrl>#styleDaimonEP0</styleUrl></Pair><Pair><key>highlight</key><styleUrl>#styleDaimonEP1</styleUrl></Pair></StyleMap>
<Style id="styleDaimonET0"><IconStyle><scale>0.60</scale><Icon><href>http://maps.google.com/mapfiles/kml/paddle/ltblu-blank.png</href></Icon><hotSpot x="1" y="32" xunits="pixels" yunits="pixels"/></IconStyle><LabelStyle><color>ffffff00</color><colorMode>normal</colorMode><scale>0.60</scale></LabelStyle><ListStyle><ItemIcon><href>http://maps.google.com/mapfiles/kml/paddle/ltblu-blank.png</href></ItemIcon></ListStyle></Style>
<Style id="styleDaimonET1"><IconStyle><scale>0.60</scale><Icon><href>http://maps.google.com/mapfiles/kml/paddle/ltblu-blank.png</href></Icon><hotSpot x="1" y="32" xunits="pixels" yunits="pixels"/></IconStyle><LabelStyle><color>ffffff00</color><colorMode>normal</colorMode><scale>0.60</scale></LabelStyle><ListStyle><ItemIcon><href>http://maps.google.com/mapfiles/kml/paddle/ltblu-blank.png</href></ItemIcon></ListStyle></Style>
<StyleMap id="mapDaimonET"><Pair><key>normal</key><styleUrl>#styleDaimonET0</styleUrl></Pair><Pair><key>highlight</key><styleUrl>#styleDaimonET1</styleUrl></Pair></StyleMap>
<Style id="styleDaimonGerador0"><IconStyle><scale>1.00</scale><Icon><href>http://maps.google.com/mapfiles/kml/paddle/wht-circle.png</href></Icon><hotSpot x="1" y="32" xunits="pixels" yunits="pixels"/></IconStyle><LabelStyle><color>ffffffff</color><colorMode>normal</colorMode><scale>1.00</scale></LabelStyle><ListStyle><ItemIcon><href>http://maps.google.com/mapfiles/kml/paddle/wht-circle.png</href></ItemIcon></ListStyle></Style>
<Style id="styleDaimonGerador1"><IconStyle><scale>1.00</scale><Icon><href>http://maps.google.com/mapfiles/kml/paddle/wht-circle.png</href></Icon><hotSpot x="1" y="32" xunits="pixels" yunits="pixels"/></IconStyle><LabelStyle><color>ffffffff</color><colorMode>normal</colorMode><scale>1.00</scale></LabelStyle><ListStyle><ItemIcon><href>http://maps.google.com/mapfiles/kml/paddle/wht-circle.png</href></ItemIcon></ListStyle></Style>
<StyleMap id="mapDaimonGerador"><Pair><key>normal</key><styleUrl>#styleDaimonGerador0</styleUrl></Pair><Pair><key>highlight</key><styleUrl>#styleDaimonGerador1</styleUrl></Pair></StyleMap>
<Style id="styleDaimonReator0"><IconStyle><scale>1.00</scale><Icon><href>http://maps.google.com/mapfiles/kml/paddle/ylw-circle.png</href></Icon><hotSpot x="1" y="32" xunits="pixels" yunits="pixels"/></IconStyle><LabelStyle><color>ff00ffff</color><colorMode>normal</colorMode><scale>1.00</scale></LabelStyle><ListStyle><ItemIcon><href>http://maps.google.com/mapfiles/kml/paddle/ylw-circle.png</href></ItemIcon></ListStyle></Style>
<Style id="styleDaimonReator1"><IconStyle><scale>1.00</scale><Icon><href>http://maps.google.com/mapfiles/kml/paddle/ylw-circle.png</href></Icon><hotSpot x="1" y="32" xunits="pixels" yunits="pixels"/></IconStyle><LabelStyle><color>ff00ffff</color><colorMode>normal</colorMode><scale>1.00</scale></LabelStyle><ListStyle><ItemIcon><href>http://maps.google.com/mapfiles/kml/paddle/ylw-circle.png</href></ItemIcon></ListStyle></Style>
<StyleMap id="mapDaimonReator"><Pair><key>normal</key><styleUrl>#styleDaimonReator0</styleUrl></Pair><Pair><key>highlight</key><styleUrl>#styleDaimonReator1</styleUrl></Pair></StyleMap>
<Style id="styleDaimonRegulador0"><IconStyle><scale>1.00</scale><Icon><href>http://maps.google.com/mapfiles/kml/paddle/wht-circle.png</href></Icon><hotSpot x="1" y="32" xunits="pixels" yunits="pixels"/></IconStyle><LabelStyle><color>ff00a5ff</color><colorMode>normal</colorMode><scale>1.00</scale></LabelStyle><ListStyle><ItemIcon><href>http://maps.google.com/mapfiles/kml/paddle/wht-circle.png</href></ItemIcon></ListStyle></Style>
<Style id="styleDaimonRegulador1"><IconStyle><scale>1.00</scale><Icon><href>http://maps.google.com/mapfiles/kml/paddle/wht-circle.png</href></Icon><hotSpot x="1" y="32" xunits="pixels" yunits="pixels"/></IconStyle><LabelStyle><color>ff00a5ff</color><colorMode>normal</colorMode><scale>1.00</scale></LabelStyle><ListStyle><ItemIcon><href>http://maps.google.com/mapfiles/kml/paddle/wht-circle.png</href></ItemIcon></ListStyle></Style>
<StyleMap id="mapDaimonRegulador"><Pair><key>normal</key><styleUrl>#styleDaimonRegulador0</styleUrl></Pair><Pair><key>highlight</key><styleUrl>#styleDaimonRegulador1</styleUrl></Pair></StyleMap>
<Style id="styleDaimonTransformador0"><IconStyle><scale>1.00</scale><Icon><href>http://maps.google.com/mapfiles/kml/paddle/pink-blank.png</href></Icon><hotSpot x="1" y="32" xunits="pixels" yunits="pixels"/></IconStyle><LabelStyle><color>ffff00ff</color><colorMode>normal</colorMode><scale>1.00</scale></LabelStyle><ListStyle><ItemIcon><href>http://maps.google.com/mapfiles/kml/paddle/pink-blank.png</href></ItemIcon></ListStyle></Style>
<Style id="styleDaimonTransformador1"><IconStyle><scale>1.00</scale><Icon><href>http://maps.google.com/mapfiles/kml/paddle/pink-blank.png</href></Icon><hotSpot x="1" y="32" xunits="pixels" yunits="pixels"/></IconStyle><LabelStyle><color>ffff00ff</color><colorMode>normal</colorMode><scale>1.00</scale></LabelStyle><ListStyle><ItemIcon><href>http://maps.google.com/mapfiles/kml/paddle/pink-blank.png</href></ItemIcon></ListStyle></Style>
<StyleMap id="mapDaimonTransformador"><Pair><key>normal</key><styleUrl>#styleDaimonTransformador0</styleUrl></Pair><Pair><key>highlight</key><styleUrl>#styleDaimonTransformador1</styleUrl></Pair></StyleMap>
<Style id="styleDaimonTrecho"><LineStyle><color>ffffffff</color><width>1.00</width></LineStyle></Style>
<Style id="styleDaimonTrechoBT"><LineStyle><color>ffff0000</color><width>1.00</width></LineStyle></Style>
<Style id="styleDaimonChaveNA0"><IconStyle><scale>0.60</scale><Icon><href>http://maps.google.com/mapfiles/kml/paddle/grn-blank.png</href></Icon><hotSpot x="1" y="32" xunits="pixels" yunits="pixels"/></IconStyle><LabelStyle><color>ff00ff00</color><colorMode>normal</colorMode><scale>0.60</scale></LabelStyle><ListStyle><ItemIcon><href>http://maps.google.com/mapfiles/kml/paddle/grn-blank.png</href></ItemIcon></ListStyle></Style>
<Style id="styleDaimonChaveNA1"><IconStyle><scale>0.60</scale><Icon><href>http://maps.google.com/mapfiles/kml/paddle/grn-blank.png</href></Icon><hotSpot x="1" y="32" xunits="pixels" yunits="pixels"/></IconStyle><LabelStyle><color>ff00ff00</color><colorMode>normal</colorMode><scale>0.60</scale></LabelStyle><ListStyle><ItemIcon><href>http://maps.google.com/mapfiles/kml/paddle/grn-blank.png</href></ItemIcon></ListStyle></Style>
<StyleMap id="mapDaimonChaveNA"><Pair><key>normal</key><styleUrl>#styleDaimonChaveNA0</styleUrl></Pair><Pair><key>highlight</key><styleUrl>#styleDaimonChaveNA1</styleUrl></Pair></StyleMap>
<Style id="styleDaimonSE0"><IconStyle><scale>1.20</scale><Icon><href>http://maps.google.com/mapfiles/kml/paddle/wht-circle.png</href></Icon><hotSpot x="1" y="32" xunits="pixels" yunits="pixels"/></IconStyle><LabelStyle><color>ffffffff</color><colorMode>normal</colorMode><scale>1.20</scale></LabelStyle><ListStyle><ItemIcon><href>http://maps.google.com/mapfiles/kml/paddle/wht-circle.png</href></ItemIcon></ListStyle></Style>
<Style id="styleDaimonSE1"><IconStyle><scale>1.20</scale><Icon><href>http://maps.google.com/mapfiles/kml/paddle/wht-circle.png</href></Icon><hotSpot x="1" y="32" xunits="pixels" yunits="pixels"/></IconStyle><LabelStyle><color>ffffffff</color><colorMode>normal</colorMode><scale>1.20</scale></LabelStyle><ListStyle><ItemIcon><href>http://maps.google.com/mapfiles/kml/paddle/wht-circle.png</href></ItemIcon></ListStyle></Style>
<StyleMap id="mapDaimonSE"><Pair><key>normal</key><styleUrl>#styleDaimonSE0</styleUrl></Pair><Pair><key>highlight</key><styleUrl>#styleDaimonSE1</styleUrl></Pair></StyleMap>
<Style id="styleDaimonCirc1Trecho"><LineStyle><color>ff00ff00</color><width>1.00</width></LineStyle></Style>
<Style id="styleDaimonCirc2Trecho"><LineStyle><color>ffff0000</color><width>1.00</width></LineStyle></Style>
<Style id="styleDaimonCirc3Trecho"><LineStyle><color>ffffff00</color><width>1.00</width></LineStyle></Style>
<Style id="styleDaimonCirc4Trecho"><LineStyle><color>ffff00ff</color><width>1.00</width></LineStyle></Style>
<Style id="styleDaimonCirc5Trecho"><LineStyle><color>ff00ffff</color><width>1.00</width></LineStyle></Style>
<Style id="styleDaimonCirc6Trecho"><LineStyle><color>ff00a5ff</color><width>1.00</width></LineStyle></Style>
<Folder>
<name>SE_VEP</name>
<open>1</open>
<Placemark><name>VEP</name><description>VERANÓPOLIS</description><LookAt><longitude>-51.545959</longitude><latitude>-28.907913</latitude><altitude>1200.0</altitude><altitudeMode>absolute</altitudeMode></LookAt><styleUrl>#mapDaimonSE</styleUrl><Point><coordinates>-51.545959,-28.907913,0</coordinates></Point></Placemark>
<Folder>
<name>Circ_VEP11</name>
<Folder>
<name>Capacitor</name>
<visibility>0</visibility>
</Folder>
<Folder>
<name>CapacitorSerie</name>
<visibility>0</visibility>
</Folder>
<Folder>
<name>Chave</name>
<visibility>0</visibility>
<Placemark><name>755347</name><visibility>0</visibility><LookAt><longitude>-51.546121</longitude><latitude>-28.907984</latitude><altitude>1200.0</altitude><altitudeMode>absolute</altitudeMode></LookAt><styleUrl>#mapDaimonChave</styleUrl><Point><coordinates>-51.546121,-28.907984,0</coordinates></Point></Placemark>
<Placemark><name>626839</name><visibility>0</visibility><LookAt><longitude>-51.539103</longitude><latitude>-28.915839</latitude><altitude>1200.0</altitude><altitudeMode>absolute</altitudeMode></LookAt><styleUrl>#mapDaimonChave</styleUrl><Point><coordinates>-51.539103,-28.915839,0</coordinates></Point></Placemark>
<Placemark><name>740888</name><visibility>0</visibility><LookAt><longitude>-51.545738</longitude><latitude>-28.908267</latitude><altitude>1200.0</altitude><altitudeMode>absolute</altitudeMode></LookAt><styleUrl>#mapDaimonChave</styleUrl><Point><coordinates>-51.545738,-28.908267,0</coordinates></Point></Placemark>
<Placemark><name>740002</name><visibility>0</visibility><LookAt><longitude>-51.539801</longitude><latitude>-28.925545</latitude><altitude>1200.0</altitude><altitudeMode>absolute</altitudeMode></LookAt><styleUrl>#mapDaimonChave</styleUrl><Point><coordinates>-51.539801,-28.925545,0</coordinates></Point></Placemark>
<Placemark><name>720628</name><visibility>0</visibility><LookAt><longitude>-51.539120</longitude><latitude>-28.915737</latitude><altitude>1200.0</altitude><altitudeMode>absolute</altitudeMode></LookAt><styleUrl>#mapDaimonChave</styleUrl><Point><coordinates>-51.539120,-28.915737,0</coordinates></Point></Placemark>
<Placemark><name>719625</name><visibility>0</visibility><LookAt><longitude>-51.539379</longitude><latitude>-28.915111</latitude><altitude>1200.0</altitude><altitudeMode>absolute</altitudeMode></LookAt><styleUrl>#mapDaimonChave</styleUrl><Point><coordinates>-51.539379,-28.915111,0</coordinates></Point></Placemark>
<Placemark><name>626836</name><visibility>0</visibility><LookAt><longitude>-51.538095</longitude><latitude>-28.920788</latitude><altitude>1200.0</altitude><altitudeMode>absolute</altitudeMode></LookAt><styleUrl>#mapDaimonChave</styleUrl><Point><coordinates>-51.538095,-28.920788,0</coordinates></Point></Placemark>
<Placemark><name>607729</name><visibility>0</visibility><LookAt><longitude>-51.545779</longitude><latitude>-28.908873</latitude><altitude>1200.0</altitude><altitudeMode>absolute</altitudeMode></LookAt><styleUrl>#mapDaimonChave</styleUrl><Point><coordinates>-51.545779,-28.908873,0</coordinates></Point></Placemark>
<Placemark><name>719541</name><visibility>0</visibility><LookAt><longitude>-51.539348</longitude><latitude>-28.925247</latitude><altitude>1200.0</altitude><altitudeMode>absolute</altitudeMode></LookAt><styleUrl>#mapDaimonChave</styleUrl><Point><coordinates>-51.539348,-28.925247,0</coordinates></Point></Placemark>
<Placemark><name>719561</name><visibility>0</visibility><LookAt><longitude>-51.541819</longitude><latitude>-28.933673</latitude><altitude>1200.0</altitude><altitudeMode>absolute</altitudeMode></LookAt><styleUrl>#mapDaimonChave</styleUrl><Point><coordinates>-51.541819,-28.933673,0</coordinates></Point></Placemark>
<Placemark><name>607722</name><visibility>0</visibility><LookAt><longitude>-51.542182</longitude><latitude>-28.935276</latitude><altitude>1200.0</altitude><altitudeMode>absolute</altitudeMode></LookAt><styleUrl>#mapDaimonChave</styleUrl><Point><coordinates>-51.542182,-28.935276,0</coordinates></Point></Placemark>
<Placemark><name>719611</name><visibility>0</visibility><LookAt><longitude>-51.540766</longitude><latitude>-28.926459</latitude><altitude>1200.0</altitude><altitudeMode>absolute</altitudeMode></LookAt><styleUrl>#mapDaimonChave</styleUrl><Point><coordinates>-51.540766,-28.926459,0</coordinates></Point></Placemark>
<Placemark><name>626833</name><visibility>0</visibility><LookAt><longitude>-51.541804</longitude><latitude>-28.930163</latitude><altitude>1200.0</altitude><altitudeMode>absolute</altitudeMode></LookAt><styleUrl>#mapDaimonChave</styleUrl><Point><coordinates>-51.541804,-28.930163,0</coordinates></Point></Placemark>
<Placemark><name>740047</name><visibility>0</visibility><LookAt><longitude>-51.542086</longitude><latitude>-28.931489</latitude><altitude>1200.0</altitude><altitudeMode>absolute</altitudeMode></LookAt><styleUrl>#mapDaimonChave</styleUrl><Point><coordinates>-51.542086,-28.931489,0</coordinates></Point></Placemark>
<Placemark><name>719597</name><visibility>0</visibility><LookAt><longitude>-51.542064</longitude><latitude>-28.931164</latitude><altitude>1200.0</altitude><altitudeMode>absolute</altitudeMode></LookAt><styleUrl>#mapDaimonChave</styleUrl><Point><coordinates>-51.542064,-28.931164,0</coordinates></Point></Placemark>
<Placemark><name>720933</name><visibility>0</visibility><LookAt><longitude>-51.541551</longitude><latitude>-28.930977</latitude><altitude>1200.0</altitude><altitudeMode>absolute</altitudeMode></LookAt><styleUrl>#mapDaimonChave</styleUrl><Point><coordinates>-51.541551,-28.930977,0</coordinates></Point></Placemark>
<Placemark><name>719609</name><visibility>0</visibility><LookAt><longitude>-51.525773</longitude><latitude>-28.923118</latitude><altitude>1200.0</altitude><altitudeMode>absolute</altitudeMode></LookAt><styleUrl>#mapDaimonChave</styleUrl><Point><coordinates>-51.525773,-28.923118,0</coordinates></Point></Placemark>
<Placemark><name>719571</name><visibility>0</visibility><LookAt><longitude>-51.538996</longitude><latitude>-28.920206</latitude><altitude>1200.0</altitude><altitudeMode>absolute</altitudeMode></LookAt><styleUrl>#mapDaimonChave</styleUrl><Point><coordinates>-51.538996,-28.920206,0</coordinates></Point></Placemark>
<Placemark><name>719591</name><visibility>0</visibility><LookAt><longitude>-51.538524</longitude><latitude>-28.922730</latitude><altitude>1200.0</altitude><altitudeMode>absolute</altitudeMode></LookAt><styleUrl>#mapDaimonChave</styleUrl><Point><coordinates>-51.538524,-28.922730,0</coordinates></Point></Placemark>
<Placemark><name>719623</name><visibility>0</visibility><LookAt><longitude>-51.539538</longitude><latitude>-28.917286</latitude><altitude>1200.0</altitude><altitudeMode>absolute</altitudeMode></LookAt><styleUrl>#mapDaimonChave</styleUrl><Point><coordinates>-51.539538,-28.917286,0</coordinates></Point></Placemark>
<Placemark><name>719593</name><visibility>0</visibility><LookAt><longitude>-51.539189</longitude><latitude>-28.919062</latitude><altitude>1200.0</altitude><altitudeMode>absolute</altitudeMode></LookAt><styleUrl>#mapDaimonChave</styleUrl><Point><coordinates>-51.539189,-28.919062,0</coordinates></Point></Placemark>
<Placemark><name>719549</name><visibility>0</visibility><LookAt><longitude>-51.539203</longitude><latitude>-28.920725</latitude><altitude>1200.0</altitude><altitudeMode>absolute</altitudeMode></LookAt><styleUrl>#mapDaimonChave</styleUrl><Point><coordinates>-51.539203,-28.920725,0</coordinates></Point></Placemark>
<Placemark><name>600398</name><visibility>0</visibility><LookAt><longitude>-51.538512</longitude><latitude>-28.923084</latitude><altitude>1200.0</altitude><altitudeMode>absolute</altitudeMode></LookAt><styleUrl>#mapDaimonChave</styleUrl><Point><coordinates>-51.538512,-28.923084,0</coordinates></Point></Placemark>
<Placemark><name>739600</name><visibility>0</visibility><LookAt><longitude>-51.542445</longitude><latitude>-28.935756</latitude><altitude>1200.0</altitude><altitudeMode>absolute</altitudeMode></LookAt><styleUrl>#mapDaimonChave</styleUrl><Point><coordinates>-51.542445,-28.935756,0</coordinates></Point></Placemark>
<Placemark><name>719583</name><visibility>0</visibility><LookAt><longitude>-51.540825</longitude><latitude>-28.928803</latitude><altitude>1200.0</altitude><altitudeMode>absolute</altitudeMode></LookAt><styleUrl>#mapDaimonChave</styleUrl><Point><coordinates>-51.540825,-28.928803,0</coordinates></Point></Placemark>
<Placemark><name>726760</name><visibility>0</visibility><LookAt><longitude>-51.541392</longitude><latitude>-28.928797</latitude><altitude>1200.0</altitude><altitudeMode>absolute</altitudeMode></LookAt><styleUrl>#mapDaimonChave</styleUrl><Point><coordinates>-51.541392,-28.928797,0</coordinates></Point></Placemark>
<Placemark><name>626842</name><visibility>0</visibility><LookAt><longitude>-51.547851</longitude><latitude>-28.932713</latitude><altitude>1200.0</altitude><altitudeMode>absolute</altitudeMode></LookAt><styleUrl>#mapDaimonChave</styleUrl><Point><coordinates>-51.547851,-28.932713,0</coordinates></Point></Placemark>
<Placemark><name>607717</name><visibility>0</visibility><LookAt><longitude>-51.548505</longitude><latitude>-28.934849</latitude><altitude>1200.0</altitude><altitudeMode>absolute</altitudeMode></LookAt><styleUrl>#mapDaimonChave</styleUrl><Point><coordinates>-51.548505,-28.934849,0</coordinates></Point></Placemark>
<Placemark><name>719607</name><visibility>0</visibility><LookAt><longitude>-51.543813</longitude><latitude>-28.929665</latitude><altitude>1200.0</altitude><altitudeMode>absolute</altitudeMode></LookAt><styleUrl>#mapDaimonChave</styleUrl><Point><coordinates>-51.543813,-28.929665,0</coordinates></Point></Placemark>
<Placemark><name>719117</name><visibility>0</visibility><LookAt><longitude>-51.540278</longitude><latitude>-28.938838</latitude><altitude>1200.0</altitude><altitudeMode>absolute</altitudeMode></LookAt><styleUrl>#mapDaimonChave</styleUrl><Point><coordinates>-51.540278,-28.938838,0</coordinates></Point></Placemark>
<Placemark><name>719089</name><visibility>0</visibility><LookAt><longitude>-51.538642</longitude><latitude>-28.938808</latitude><altitude>1200.0</altitude><altitudeMode>absolute</altitudeMode></LookAt><styleUrl>#mapDaimonChave</styleUrl><Point><coordinates>-51.538642,-28.938808,0</coordinates></Point></Placemark>
<Placemark><name>719085</name><visibility>0</visibility><LookAt><longitude>-51.541268</longitude><latitude>-28.938856</latitude><altitude>1200.0</altitude><altitudeMode>absolute</altitudeMode></LookAt><styleUrl>#mapDaimonChave</styleUrl><Point><coordinates>-51.541268,-28.938856,0</coordinates></Point></Placemark>
<Placemark><name>719103</name><visibility>0</visibility><LookAt><longitude>-51.543795</longitude><latitude>-28.938909</latitude><altitude>1200.0</altitude><altitudeMode>absolute</altitudeMode></LookAt><styleUrl>#mapDaimonChave</styleUrl><Point><coordinates>-51.543795,-28.938909,0</coordinates></Point></Placemark>
<Placemark><name>739602</name><visibility>0</visibility><LookAt><longitude>-51.551189</longitude><latitude>-28.943422</latitude><altitude>1200.0</altitude><altitudeMode>absolute</altitudeMode></LookAt><styleUrl>#mapDaimonChave</styleUrl><Point><coordinates>-51.551189,-28.943422,0</coordinates></Point></Placemark>
<Placemark><name>752178</name><visibility>0</visibility><LookAt><longitude>-51.548871</longitude><latitude>-28.941567</latitude><altitude>1200.0</altitude><altitudeMode>absolute</altitudeMode></LookAt><styleUrl>#mapDaimonChave</styleUrl><Point><coordinates>-51.548871,-28.941567,0</coordinates></Point></Placemark>
<Placemark><name>719565</name><visibility>0</visibility><LookAt><longitude>-51.542341</longitude><latitude>-28.932591</latitude><altitude>1200.0</altitude><altitudeMode>absolute</altitudeMode></LookAt><styleUrl>#mapDaimonChave</styleUrl><Point><coordinates>-51.542341,-28.932591,0</coordinates></Point></Placemark>
<Placemark><name>719539</name><visibility>0</visibility><LookAt><longitude>-51.546596</longitude><latitude>-28.932665</latitude><altitude>1200.0</altitude><altitudeMode>absolute</altitudeMode></LookAt><styleUrl>#mapDaimonChave</styleUrl><Point><coordinates>-51.546596,-28.932665,0</coordinates></Point></Placemark>
<Placemark><name>600279</name><visibility>0</visibility><LookAt><longitude>-51.545857</longitude><latitude>-28.932653</latitude><altitude>1200.0</altitude><altitudeMode>absolute</altitudeMode></LookAt><styleUrl>#mapDaimonChave</styleUrl><Point><coordinates>-51.545857,-28.932653,0</coordinates></Point></Placemark>
<Placemark><name>719581</name><visibility>0</visibility><LookAt><longitude>-51.545020</longitude><latitude>-28.932641</latitude><altitude>1200.0</altitude><altitudeMode>absolute</altitudeMode></LookAt><styleUrl>#mapDaimonChave</styleUrl><Point><coordinates>-51.545020,-28.932641,0</coordinates></Point></Placemark>
<Placemark><name>607716</name><visibility>0</visibility><LookAt><longitude>-51.548476</longitude><latitude>-28.936005</latitude><altitude>1200.0</altitude><altitudeMode>absolute</altitudeMode></LookAt><styleUrl>#mapDaimonChave</styleUrl><Point><coordinates>-51.548476,-28.936005,0</coordinates></Point></Placemark>
<Placemark><name>607731</name><visibility>0</visibility><LookAt><longitude>-51.545813</longitude><latitude>-28.934990</latitude><altitude>1200.0</altitude><altitudeMode>absolute</altitudeMode></LookAt><styleUrl>#mapDaimonChave</styleUrl><Point><coordinates>-51.545813,-28.934990,0</coordinates></Point></Placemark>
<Placemark><name>739845</name><visibility>0</visibility><LookAt><longitude>-51.546748</longitude><latitude>-28.934849</latitude><altitude>1200.0</altitude><altitudeMode>absolute</altitudeMode></LookAt><styleUrl>#mapDaimonChave</styleUrl><Point><coordinates>-51.546748,-28.934849,0</coordinates></Point></Placemark>
<Placemark><name>719551</name><visibility>0</visibility><LookAt><longitude>-51.549520</longitude><latitude>-28.935043</latitude><altitude>1200.0</altitude><altitudeMode>absolute</altitudeMode></LookAt><styleUrl>#mapDaimonChave</styleUrl><Point><coordinates>-51.549520,-28.935043,0</coordinates></Point></Placemark>
<Placemark><name>719577</name><visibility>0</visibility><LookAt><longitude>-51.549264</longitude><latitude>-28.935055</latitude><altitude>1200.0</altitude><altitudeMode>absolute</altitudeMode></LookAt><styleUrl>#mapDaimonChave</styleUrl><Point><coordinates>-51.549264,-28.935055,0</coordinates></Point></Placemark>
<Placemark><name>745632</name><visibility>0</visibility><LookAt><longitude>-51.551972</longitude><latitude>-28.945435</latitude><altitude>1200.0</altitude><altitudeMode>absolute</altitudeMode></LookAt><styleUrl>#mapDaimonChave</styleUrl><Point><coordinates>-51.551972,-28.945435,0</coordinates></Point></Placemark>
<Placemark><name>719151</name><visibility>0</visibility><LookAt><longitude>-51.549739</longitude><latitude>-28.942369</latitude><altitude>1200.0</altitude><altitudeMode>absolute</altitudeMode></LookAt><styleUrl>#mapDaimonChave</styleUrl><Point><coordinates>-51.549739,-28.942369,0</coordinates></Point></Placemark>
<Placemark><name>719087</name><visibility>0</visibility><LookAt><longitude>-51.546927</longitude><latitude>-28.941529</latitude><altitude>1200.0</altitude><altitudeMode>absolute</altitudeMode></LookAt><styleUrl>#mapDaimonChave</styleUrl><Point><coordinates>-51.546927,-28.941529,0</coordinates></Point></Placemark>
<Placemark><name>719141</name><visibility>0</visibility><LookAt><longitude>-51.549156</longitude><latitude>-28.942380</latitude><altitude>1200.0</altitude><altitudeMode>absolute</altitudeMode></LookAt><styleUrl>#mapDaimonChave</styleUrl><Point><coordinates>-51.549156,-28.942380,0</coordinates></Point></Placemark>
<Placemark><name>719579</name><visibility>0</visibility><LookAt><longitude>-51.548107</longitude><latitude>-28.937102</latitude><altitude>1200.0</altitude><altitudeMode>absolute</altitudeMode></LookAt><styleUrl>#mapDaimonChave</styleUrl><Point><coordinates>-51.548107,-28.937102,0</coordinates></Point></Placemark>
<Placemark><name>775691</name><visibility>0</visibility><LookAt><longitude>-51.546729</longitude><latitude>-28.933722</latitude><altitude>1200.0</altitude><altitudeMode>absolute</altitudeMode></LookAt><styleUrl>#mapDaimonChave</styleUrl><Point><coordinates>-51.546729,-28.933722,0</coordinates></Point></Placemark>
<Placemark><name>719109</name><visibility>0</visibility><LookAt><longitude>-51.553428</longitude><latitude>-28.952286</latitude><altitude>1200.0</altitude><altitudeMode>absolute</altitudeMode></LookAt><styleUrl>#mapDaimonChave</styleUrl><Point><coordinates>-51.553428,-28.952286,0</coordinates></Point></Placemark>
<Placemark><name>626332</name><visibility>0</visibility><LookAt><longitude>-51.551868</longitude><latitude>-28.948873</latitude><altitude>1200.0</altitude><altitudeMode>absolute</altitudeMode></LookAt><styleUrl>#mapDaimonChave</styleUrl><Point><coordinates>-51.551868,-28.948873,0</coordinates></Point></Placemark>
<Placemark><name>719101</name><visibility>0</visibility><LookAt><longitude>-51.552903</longitude><latitude>-28.953494</latitude><altitude>1200.0</altitude><altitudeMode>absolute</altitudeMode></LookAt><styleUrl>#mapDaimonChave</styleUrl><Point><coordinates>-51.552903,-28.953494,0</coordinates></Point></Placemark>
<Placemark><name>626328</name><visibility>0</visibility><LookAt><longitude>-51.552774</longitude><latitude>-28.955314</latitude><altitude>1200.0</altitude><altitudeMode>absolute</altitudeMode></LookAt><styleUrl>#mapDaimonChave</styleUrl><Point><coordinates>-51.552774,-28.955314,0</coordinates></Point></Placemark>
<Placemark><name>626340</name><visibility>0</visibility><LookAt><longitude>-51.552849</longitude><latitude>-28.954032</latitude><altitude>1200.0</altitude><altitudeMode>absolute</altitudeMode></LookAt><styleUrl>#mapDaimonChave</styleUrl><Point><coordinates>-51.552849,-28.954032,0</coordinates></Point></Placemark>
<Placemark><name>607616</name><visibility>0</visibility><LookAt><longitude>-51.553573</longitude><latitude>-28.947176</latitude><altitude>1200.0</altitude><altitudeMode>absolute</altitudeMode></LookAt><styleUrl>#mapDaimonChave</styleUrl><Point><coordinates>-51.553573,-28.947176,0</coordinates></Point></Placemark>
<Placemark><name>719105</name><visibility>0</visibility><LookAt><longitude>-51.548428</longitude><latitude>-28.947921</latitude><altitude>1200.0</altitude><altitudeMode>absolute</altitudeMode></LookAt><styleUrl>#mapDaimonChave</styleUrl><Point><coordinates>-51.548428,-28.947921,0</coordinates></Point></Placemark>
<Placemark><name>626353</name><visibility>0</visibility><LookAt><longitude>-51.547058</longitude><latitude>-28.969173</latitude><altitude>1200.0</altitude><altitudeMode>absolute</altitudeMode></LookAt><styleUrl>#mapDaimonChave</styleUrl><Point><coordinates>-51.547058,-28.969173,0</coordinates></Point></Placemark>
<Placemark><name>626362</name><visibility>0</visibility><LookAt><longitude>-51.546957</longitude><latitude>-28.964572</latitude><altitude>1200.0</altitude><altitudeMode>absolute</altitudeMode></LookAt><styleUrl>#mapDaimonChave</styleUrl><Point><coordinates>-51.546957,-28.964572,0</coordinates></Point></Placemark>
<Placemark><name>626351</name><visibility>0</visibility><LookAt><longitude>-51.549676</longitude><latitude>-28.956650</latitude><altitude>1200.0</altitude><altitudeMode>absolute</altitudeMode></LookAt><styleUrl>#mapDaimonChave</styleUrl><Point><coordinates>-51.549676,-28.956650,0</coordinates></Point></Placemark>
<Placemark><name>719095</name><visibility>0</visibility><LookAt><longitude>-51.553833</longitude><latitude>-28.947381</latitude><altitude>1200.0</altitude><altitudeMode>absolute</altitudeMode></LookAt><styleUrl>#mapDaimonChave</styleUrl><Point><coordinates>-51.553833,-28.947381,0</coordinates></Point></Placemark>
<Placemark><name>755978</name><visibility>0</visibility><LookAt><longitude>-51.557273</longitude><latitude>-28.950420</latitude><altitude>1200.0</altitude><altitudeMode>absolute</altitudeMode></LookAt><styleUrl>#mapDaimonChave</styleUrl><Point><coordinates>-51.557273,-28.950420,0</coordinates></Point></Placemark>
<Placemark><name>745315</name><visibility>0</visibility><LookAt><longitude>-51.556900</longitude><latitude>-28.950157</latitude><altitude>1200.0</altitude><altitudeMode>absolute</altitudeMode></LookAt><styleUrl>#mapDaimonChave</styleUrl><Point><coordinates>-51.556900,-28.950157,0</coordinates></Point></Placemark>
<Placemark><name>607726</name><visibility>0</visibility><LookAt><longitude>-51.542021</longitude><latitude>-28.934993</latitude><altitude>1200.0</altitude><altitudeMode>absolute</altitudeMode></LookAt><styleUrl>#mapDaimonChaveNA</styleUrl><Point><coordinates>-51.542021,-28.934993,0</coordinates></Point></Placemark>
</Folder>
